/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false cloudflare-env.d.ts` (hash: 1fe37f15923541547152fcaebf9a6e99)
interface __BaseEnv_Env {
	ALICE_RATE_LIMITER: RateLimit;
	ALICE_TURNSTILE_SITE_KEY: "0x4AAAAAAD2asv23rUpmvSTk";
	ALICE_BETA_ENABLED: "true";
	ALICE_BETA_LABEL: "Beta";
	ALICE_ADVISOR_SERVICE: Fetcher /* afft-growth-os */;
}
declare namespace Cloudflare {
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
