"use client";
import { useEffect, useMemo, useState } from "react";
import { createInquiryRef, formatInquiryRef, trackEvent } from "@/lib/analytics";
import { offers } from "@/lib/offers";
import { makeWhatsappLink } from "@/lib/rent-it-data";

const serviceOptions = [{label:"露营套餐",value:"Camping package"},{label:"Rent It 装备",value:"Rent It gear"},{label:"私人行程",value:"Private tour"},{label:"租车／包车",value:"Car rental / charter"}] as const;
export function ZhWhatsAppEnquiryBuilder({title="先把需要的资料发给 AFFT",text="回答几个实际问题，让 AFFT 更快提供合适方案。",defaultService="Camping package",defaultInterest=""}:{title?:string;text?:string;defaultService?:string;defaultInterest?:string;services?:{label:string;value:string}[]}){
 const [service,setService]=useState(defaultService); const [offerId,setOfferId]=useState(""); const [date,setDate]=useState(""); const [guests,setGuests]=useState(""); const [location,setLocation]=useState(""); const [budget,setBudget]=useState(""); const [interest,setInterest]=useState(defaultInterest); const [addOns,setAddOns]=useState(""); const [copied,setCopied]=useState(false); const [refLine,setRefLine]=useState("REF: 正在准备网站来源");
 useEffect(()=>{setRefLine(formatInquiryRef(createInquiryRef("zh",offerId||"GENERAL")))},[offerId]);
 const message=useMemo(()=>["你好 AFFT，我想安排沙巴体验。","",`服务：${serviceOptions.find(x=>x.value===service)?.label||service}`,offerId?`套餐：${offerId}`:"",`日期：${date||"未确认"}`,`人数：${guests||"未确认"}`,`地点／接送：${location||"未确认"}`,`预算：${budget||"请建议"}`,`需求：${interest||"请推荐"}`,`加购：${addOns||"暂时没有"}`,"",refLine,"","请回复供应情况、价格和下一步。"].filter(Boolean).join("\n"),[addOns,budget,date,guests,interest,location,offerId,refLine,service]);
 return <section className="rounded-[2rem] border border-[#F3922B]/20 bg-[#182015] p-6 md:p-8" onFocusCapture={()=>trackEvent("start_enquiry",{service})}><div className="grid gap-8 xl:grid-cols-[.8fr_1.2fr]"><div><p className="text-sm font-bold uppercase tracking-[.3em] text-[#F3922B]">WhatsApp Builder 2.0</p><h2 className="mt-3 text-3xl font-bold md:text-4xl">{title}</h2><p className="mt-4 text-white/70">{text}</p><p className="mt-4 text-sm text-white/45">无需注册，网站不会储存这里填写的答案。</p></div><div className="grid gap-4"><div className="grid gap-4 md:grid-cols-2">
 <Field label="服务"><select value={service} onChange={e=>{setService(e.target.value);setOfferId("")}} className={control}>{serviceOptions.map(x=><option key={x.value} value={x.value}>{x.label}</option>)}</select></Field>
 {service==="Camping package"?<Field label="套餐"><select value={offerId} onChange={e=>setOfferId(e.target.value)} className={control}><option value="">请 AFFT 推荐</option>{offers.filter(x=>x.category==="camping").map(x=><option key={x.offerId} value={x.offerId}>{x.locales.zh.name} — {x.priceType==="custom"?"定制报价":x.priceType==="fixed"?`RM${x.priceFrom}`:`RM${x.priceFrom} 起`}</option>)}</select></Field>:null}
 <Field label="日期"><input value={date} onChange={e=>setDate(e.target.value)} placeholder="例如：2026年8月12日" className={control}/></Field><Field label="人数"><input value={guests} onChange={e=>setGuests(e.target.value)} placeholder="2位成人、1位儿童" className={control}/></Field><Field label="地点／接送"><input value={location} onChange={e=>setLocation(e.target.value)} placeholder="酒店、营地或路线" className={control}/></Field><Field label="预算"><input value={budget} onChange={e=>setBudget(e.target.value)} placeholder="例如：RM600–900" className={control}/></Field></div>
 <Field label="具体需求"><input value={interest} onChange={e=>setInterest(e.target.value)} placeholder="告诉我们最重要的需求" className={control}/></Field><Field label="可选加购"><input value={addOns} onChange={e=>setAddOns(e.target.value)} placeholder="交通、餐食、摄影装备或额外帐篷" className={control}/></Field>
 <div className="rounded-2xl border border-white/10 bg-black/20 p-4"><p className="text-xs font-bold uppercase tracking-[.24em] text-white/45">讯息预览</p><pre className="mt-3 max-h-72 overflow-auto whitespace-pre-wrap font-sans text-sm leading-6 text-white/75">{message}</pre></div><div className="flex flex-wrap gap-3"><a href={makeWhatsappLink(message)} target="_blank" rel="noreferrer" className="rounded-full bg-[#F3922B] px-6 py-3 font-bold text-black">打开 WhatsApp</a><button type="button" onClick={async()=>{await navigator.clipboard?.writeText(message);trackEvent("copy_message",{service,offer_id:offerId||"GENERAL"});setCopied(true);setTimeout(()=>setCopied(false),1600)}} className="rounded-full border border-white/15 px-6 py-3 font-bold">{copied?"已复制":"复制讯息"}</button></div>
 </div></div></section>
}
const control="w-full rounded-2xl border border-white/10 bg-black/25 px-4 py-3 text-white outline-none placeholder:text-white/35 focus:border-[#F3922B]";
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="block"><span className="mb-2 block text-sm font-bold text-white/70">{label}</span>{children}</label>}
